name: pickeat
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.2.1
  flutter_riverpod: ^2.5.1

  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1

  image_picker: ^1.1.2
  intl: ^0.19.0
  dots_indicator: ^3.0.0

  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  flutter_image_compress: ^2.3.0

  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  video_player: ^2.9.1
  chewie: ^1.8.1
  preload_page_view: ^0.2.0

  amplitude_flutter: ^3.16.2
  app_tracking_transparency: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/image/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
     - family: Schyler
       fonts:
         - asset: fonts/Schyler-Regular.ttf
         - asset: fonts/Schyler-Italic.ttf
           style: italic
     - family: Trajan Pro
       fonts:
         - asset: fonts/TrajanPro.ttf
         - asset: fonts/TrajanPro_Bold.ttf
           weight: 700
     - family: Pretendard
       fonts:
          - asset: assets/fonts/Pretendard-Thin.ttf
            weight: 100
          - asset: assets/fonts/Pretendard-Light.ttf
            weight: 300
          - asset: assets/fonts/Pretendard-Regular.ttf
            weight: 400
          - asset: assets/fonts/Pretendard-Medium.ttf
            weight: 500
          - asset: assets/fonts/Pretendard-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Pretendard-Bold.ttf
            weight: 700
          - asset: assets/fonts/Pretendard-ExtraBold.ttf
            weight: 800
          - asset: fonts/Pretendard-Black.ttf
            weight: 900

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
