// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrvHvRc18TWSCxPyG9KZ3Gx4kAr0BzRv0',
    appId: '1:501552850338:web:fd7dafdc4d6ec69ba6fefb',
    messagingSenderId: '501552850338',
    projectId: 'anyway-pickeat',
    authDomain: 'anyway-pickeat.firebaseapp.com',
    storageBucket: 'anyway-pickeat.appspot.com',
    measurementId: 'G-4ZSD0DRFGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYHhaAqrcQvfBIF4NPiNy27pV1zWqKTvo',
    appId: '1:501552850338:android:8b82aa53760358e2a6fefb',
    messagingSenderId: '501552850338',
    projectId: 'anyway-pickeat',
    storageBucket: 'anyway-pickeat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzJDswKZxWZcPZN4h7RQRQLdRDJVElS3s',
    appId: '1:501552850338:ios:c72f2740094f691da6fefb',
    messagingSenderId: '501552850338',
    projectId: 'anyway-pickeat',
    storageBucket: 'anyway-pickeat.appspot.com',
    androidClientId: '501552850338-auu1s9t6ru1350f39kl98olk8o7lb5j1.apps.googleusercontent.com',
    iosClientId: '501552850338-b3s1c2htju2tnbl7h4qlkd5je1pefho4.apps.googleusercontent.com',
    iosBundleId: 'com.anyway.pickeat.pickeat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzJDswKZxWZcPZN4h7RQRQLdRDJVElS3s',
    appId: '1:501552850338:ios:c72f2740094f691da6fefb',
    messagingSenderId: '501552850338',
    projectId: 'anyway-pickeat',
    storageBucket: 'anyway-pickeat.appspot.com',
    androidClientId: '501552850338-auu1s9t6ru1350f39kl98olk8o7lb5j1.apps.googleusercontent.com',
    iosClientId: '501552850338-b3s1c2htju2tnbl7h4qlkd5je1pefho4.apps.googleusercontent.com',
    iosBundleId: 'com.anyway.pickeat.pickeat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrvHvRc18TWSCxPyG9KZ3Gx4kAr0BzRv0',
    appId: '1:501552850338:web:75f4920b0b9efddea6fefb',
    messagingSenderId: '501552850338',
    projectId: 'anyway-pickeat',
    authDomain: 'anyway-pickeat.firebaseapp.com',
    storageBucket: 'anyway-pickeat.appspot.com',
    measurementId: 'G-YJGX9JYYR9',
  );

}